### ISSUE TITLE
ChillerDragon:pr_07_client skin render issues and log spam

### ISSUE THREAD

**Issue by SoulyVEVO** [ChillerDragon/ddnet#10]
- When in solo parts only weapons and name get transparency changes (again not sure if thats really an issue)
![screenshot_2024-07-21_13-16-47](https://github.com/user-attachments/assets/7363ed0d-bafc-4c14-b241-43dc8ce11c19)

**Comment by ChillerDragon** [comment]
Nice findings thanks for the detailed report.

**Comment by ChillerDragon** [comment]
> So basically im not sure how many of those are caused by the client itself and not by server not sending certain data to the client.

Yea some of the findings apply only to custom servers but thats still a valid finding. Even if the server sends weird things, the result would ideally be the same as in the vanilla 0.7 client.

**Comment by SoulyVEVO** [comment]
Another issue i found is that Free-View option in spectator menu simply doesnt work on 0.7 based servers (also theres no option to spectate flags but thats rather not a bug so its fine i think)
![screenshot_2024-07-21_23-00-06](https://github.com/user-attachments/assets/6fffc01c-ad03-47d7-b445-fd7eaab08eb3)

**Comment by SoulyVEVO** [comment]
also times in scoreboard seem to be sorted from highiest to lowest and people who havent finished have times displayed as 00.00
![screenshot_2024-07-21_23-11-59](https://github.com/user-attachments/assets/e15f057e-3261-49a1-bc2f-1fa3e000c978)

**Comment by ChillerDragon** [comment]
Fixed transparency in solo parts.

![screenshot_2024-07-22_10-07-43](https://github.com/user-attachments/assets/a3f0d89f-c30f-4919-89d4-55a9284f6536)
