### ISSUE TITLE
ChillerDragon:pr_07_client wrong weapon displayed in fng

### ISSUE THREAD

**Issue by ChillerDragon** [ChillerDragon/ddnet#13]
When joining fng weapon shows up as gun while laser crosshair is displayed

**Comment by SoulyVEVO** [comment]
also antiping seems to think that gun is still in players inventory and its displayed for a short time when scrolling through weapons
![screenshot_2024-07-21_13-41-32](https://github.com/user-attachments/assets/a4bd2b50-1330-4aa2-82cc-a9c1c966ae2a)

**Comment by ChillerDragon** [comment]
To reproduce `cl_antiping` needs to be set to `1`

**Comment by ChillerDragon** [comment]
I can not reproduce that issue on [ddnet-insta](https://github.com/ddnet-insta/ddnet-insta) servers. I noticed that onbgy fng does not send a ddnet ex character which would include weapon information.

**Comment by ChillerDragon** [comment]
Found the bug. So the jetpack tuning variable was set in the wrong spot. It was set before the tunings were red. Meaning it would be overwritten by the read and basically not set at all. If the jetpack strength tuning is not explicitly set to 0 on a non ddnet server (which does not send the ddnet ex character items) it will be 100 by default and then the ddnet client assumes it has jetpack which will add the gun to the inventory.

```diff
diff --git a/src/game/client/gameclient.cpp b/src/game/client/gameclient.cpp
index 2d7bbb366..ad3ea3ef0 100644
--- a/src/game/client/gameclient.cpp
+++ b/src/game/client/gameclient.cpp
@@ -861,8 +861,6 @@ void CGameClient::OnMessage(int MsgId, CUnpacker *pUnpacker, int Conn, bool Dumm
                // unpack the new tuning
                CTuningParams NewTuning;
                int *pParams = (int *)&NewTuning;
-               // No jetpack on DDNet incompatible servers:
-               NewTuning.m_JetpackStrength = 0;
                for(unsigned i = 0; i < sizeof(CTuningParams) / sizeof(int); i++)
                {
                        // 31 is the magic number index of laser_damage
@@ -877,6 +875,9 @@ void CGameClient::OnMessage(int MsgId, CUnpacker *pUnpacker, int Conn, bool Dumm
                        pParams[i] = value;
                }
 
+               // No jetpack on DDNet incompatible servers:
+               NewTuning.m_JetpackStrength = 0;
+
                m_ServerMode = SERVERMODE_PURE;
 
                m_aReceivedTuning[Conn] = true;
```
