### ISSUE TITLE
ChillerDragon:pr_07_client Ninja skin defaults to 0.6 format

### ISSUE THREAD

**Issue by SoulyVEVO** [ChillerDragon/ddnet#15]
0.6 ninja skin is being used when connecting with 0.7
![screenshot_2024-07-21_13-10-49](https://github.com/user-attachments/assets/f5c9718c-d5f3-4a63-bb12-81a9cb90c5ad)

**Comment by ChillerDragon** [comment]
I am not sure if that one is worth the effort or if it can be sold as feature. Maybe users who play with ddnet instead of the teeworlds client actually prefer the old look? Is there an advantage of showing the 0.7 version? Could it have custom markings or something like that?

**Comment by SoulyVEVO** [comment]
i guess theres no real reason other than than looks

**Comment by ChillerDragon** [comment]
I will close this as not planned. Until someone actually complains about it.
