### ISSUE TITLE
ChillerDragon:pr_07_client Tee hands image defaults to 0.6 format

### ISSUE THREAD

**Issue by SoulyVEVO** [ChillerDragon/ddnet#16]
it looks like 0.6 hands are being used instead of 0.7 ones, custom colors or shapes for hands dont show up
![screenshot_2024-07-21_13-39-33](https://github.com/user-attachments/assets/f91f89c1-c472-4763-be41-dd046afef5ae)

**Comment by ChillerDragon** [comment]
![image](https://github.com/user-attachments/assets/ee965029-d500-40b7-a0bc-ee72e32c191c)

done
