### ISSUE TITLE
ChillerDragon:pr_07_client Need to dilate skin images

### ISSUE THREAD

**Issue by SoulyVEVO** [ChillerDragon/ddnet#18]
![screenshot_2024-07-22_04-55-03](https://github.com/user-attachments/assets/e17b4b41-ce2c-4046-9be7-f3dcbee8c334)

**Comment by ChillerDragon** [comment]
All the images in the pr_07_client branch should be dilated already. Whats that skin? [dog.png](https://github.com/ChillerDragon/ddnet/blob/1c43b927b20e5c460956aa94a03cce55a63c8360/data/skins7/body/dog.png)?

Not sure what to do here.

**Comment by SoulyVEVO** [comment]
weird, i dilated them myself and only then it started looking like it should

**Comment by ChillerDragon** [comment]
Could you send one dilated image I would like to see the diff. The dilate tool should work the same for both of us.

**Comment by SoulyVEVO** [comment]
turns out it was issue from my side when moving skins from vanilla, everything is fine
