### ISSUE TITLE
ctf2 and dm3 has missing tiles

### ISSUE THREAD

**Issue by M0REKZ** [ChillerDragon/ddnet#8]
Some bugs in the screenshots, other maps could be affected by this too.

![1](https://github.com/ChillerDragon/ddnet/assets/60852359/e3d730ab-6684-403e-a78a-7fd993fe6501)
![2](https://github.com/ChillerDragon/ddnet/assets/60852359/fb0aa39b-9f40-4f70-bbe5-738121b6e80c)
![3l](https://github.com/ChillerDragon/ddnet/assets/60852359/c88661cd-ec18-4700-8987-9efaaabf720c)

**Comment by ChillerDragon** [comment]
I assume this is for the ddnet 0.7 client. Thanks for reporting I will look into it. :slightly_smiling_face:

**Comment by ChillerDragon** [comment]
Fixed and did a new release at https://chillerdragon.github.io/ddnet7-client/
